FUENTES_NOTICIAS = [{'id': 'la_jornada',
  'nombre': 'La Jornada',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://www.jornada.com.mx',
  'urls': ['https://www.jornada.com.mx/rss/edicion.xml',
           'https://www.jornada.com.mx/rss/ultimas.xml'],
  'dominios_permitidos': ['www.jornada.com.mx', 'jornada.com.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Fuente RSS sindicada. Algunas secciones pueden cambiar su ruta RSS.'},
 {'id': 'aristegui_noticias',
  'nombre': 'Aristegui Noticias',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://editorial.aristeguinoticias.com',
  'urls': ['https://editorial.aristeguinoticias.com/feed/',
           'https://editorial.aristeguinoticias.com/category/mexico/feed/',
           'https://editorial.aristeguinoticias.com/category/mundo/feed/'],
  'dominios_permitidos': ['editorial.aristeguinoticias.com'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Usa feeds RSS editoriales oficiales por portada, México y Mundo.'},
 {'id': 'proceso',
  'nombre': 'Proceso',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://www.proceso.com.mx',
  'urls': ['https://www.proceso.com.mx/rss'],
  'dominios_permitidos': ['www.proceso.com.mx', 'proceso.com.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed RSS general. La disponibilidad depende del proveedor.'},
 {'id': 'heraldo_mexico',
  'nombre': 'El Heraldo de México',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://heraldodemexico.com.mx',
  'urls': ['https://heraldodemexico.com.mx/rss/', 'https://heraldodemexico.com.mx/rss/feed.html'],
  'dominios_permitidos': ['heraldodemexico.com.mx', 'www.heraldodemexico.com.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Canales RSS públicos. Puede requerir ajuste si el sitio cambia sus feeds.'},
 {'id': 'el_pais_mexico',
  'nombre': 'El País México',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://elpais.com/mexico/',
  'urls': ['https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/mexico/portada',
           'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ultimas-noticias/portada',
           'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/tecnologia/portada'],
  'dominios_permitidos': ['elpais.com', 'www.elpais.com', 'feeds.elpais.com'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feeds RSS oficiales de EL PAÍS: edición México, últimas noticias y tecnología.'},
 {'id': 'bbc_mundo',
  'nombre': 'BBC Mundo',
  'tipo': 'rss',
  'pais': 'Internacional',
  'idioma': 'es',
  'base_url': 'https://www.bbc.com',
  'urls': ['https://feeds.bbci.co.uk/mundo/rss.xml'],
  'dominios_permitidos': ['www.bbc.com', 'bbc.com'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed RSS oficial de BBC en español.'},
 {'id': 'el_universal',
  'nombre': 'El Universal',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://www.eluniversal.com.mx',
  'urls': ['https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml'],
  'dominios_permitidos': ['www.eluniversal.com.mx', 'eluniversal.com.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed RSS general del diario mexicano El Universal.'},
 {'id': 'expansion',
  'nombre': 'Expansión',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://expansion.mx',
  'urls': ['https://expansion.mx/rss'],
  'dominios_permitidos': ['expansion.mx', 'www.expansion.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed RSS de Expansión, enfocado en negocios y economía.'},
 {'id': 'milenio',
  'nombre': 'Milenio',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://www.milenio.com',
  'urls': ['https://www.milenio.com/rss/tecnologia', 'https://www.milenio.com/rss/negocios'],
  'dominios_permitidos': ['www.milenio.com', 'milenio.com'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feeds RSS de Tecnología y Economía de Milenio.'},
 {'id': 'excelsior',
  'nombre': 'Excélsior',
  'tipo': 'rss',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://www.excelsior.com.mx',
  'urls': ['https://www.excelsior.com.mx/rss.xml'],
  'dominios_permitidos': ['www.excelsior.com.mx', 'excelsior.com.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed RSS general del diario Excélsior.'},
 {'id': 'reuters_es',
  'nombre': 'Reuters ES',
  'tipo': 'rss',
  'pais': 'Internacional',
  'idioma': 'en',
  'base_url': 'https://feeds.reuters.com',
  'urls': ['https://feeds.reuters.com/reuters/MXeconomicsNews'],
  'dominios_permitidos': ['feeds.reuters.com', 'reuters.com'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed de Reuters con noticias económicas sobre México (en inglés).'},
 {'id': 'nasa',
  'nombre': 'NASA',
  'tipo': 'rss',
  'pais': 'Internacional',
  'idioma': 'en',
  'base_url': 'https://www.nasa.gov',
  'urls': ['https://www.nasa.gov/rss/dyn/breaking_news.rss'],
  'dominios_permitidos': ['www.nasa.gov', 'nasa.gov'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Feed RSS de noticias de última hora de la NASA (en inglés).'},
 {'id': 'inegi_sala_prensa',
  'nombre': 'INEGI Sala de Prensa',
  'tipo': 'html',
  'pais': 'México',
  'idioma': 'es',
  'base_url': 'https://www.inegi.org.mx',
  'urls': ['https://www.inegi.org.mx/app/saladeprensa/'],
  'dominios_permitidos': ['www.inegi.org.mx', 'inegi.org.mx'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': True,
  'notas': 'Página HTML institucional; puede requerir parser específico si cambia el DOM.'},
 {'id': 'feeds',
  'nombre': 'Feeds',
  'tipo': 'rss',
  'pais': 'Personalizada',
  'idioma': 'es',
  'base_url': 'https://feeds.elpais.com',
  'urls': ['https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada'],
  'dominios_permitidos': ['feeds.elpais.com'],
  'activo': True,
  'limite_noticias': 20,
  'delay_segundos': 3,
  'requiere_parser_html': False,
  'notas': 'Fuente guardada desde Custom RSS/URL.'}]
