FUENTES_NOTICIAS = [
    {
        "id": "la_jornada",
        "nombre": "La Jornada",
        "tipo": "rss",
        "pais": "México",
        "idioma": "es",
        "base_url": "https://www.jornada.com.mx",
        "urls": [
            "https://www.jornada.com.mx/rss/edicion.xml",
            "https://www.jornada.com.mx/rss/ultimas.xml",
        ],
        "dominios_permitidos": ["www.jornada.com.mx", "jornada.com.mx"],
        "activo": True,
        "limite_noticias": 20,
        "delay_segundos": 3,
        "requiere_parser_html": False,
        "notas": "Fuente RSS sindicada. Algunas secciones pueden cambiar su ruta RSS.",
    },
    {
        "id": "aristegui_noticias",
        "nombre": "Aristegui Noticias",
        "tipo": "rss",
        "pais": "México",
        "idioma": "es",
        "base_url": "https://editorial.aristeguinoticias.com",
        "urls": [
            "https://editorial.aristeguinoticias.com/feed/",
            "https://editorial.aristeguinoticias.com/category/mexico/feed/",
            "https://editorial.aristeguinoticias.com/category/mundo/feed/",
        ],
        "dominios_permitidos": ["editorial.aristeguinoticias.com"],
        "activo": True,
        "limite_noticias": 20,
        "delay_segundos": 3,
        "requiere_parser_html": False,
        "notas": "Usa feeds RSS editoriales oficiales por portada, México y Mundo.",
    },
    {
        "id": "proceso",
        "nombre": "Proceso",
        "tipo": "rss",
        "pais": "México",
        "idioma": "es",
        "base_url": "https://www.proceso.com.mx",
        "urls": [
            "https://www.proceso.com.mx/rss",
        ],
        "dominios_permitidos": ["www.proceso.com.mx", "proceso.com.mx"],
        "activo": True,
        "limite_noticias": 20,
        "delay_segundos": 3,
        "requiere_parser_html": False,
        "notas": "Feed RSS general. La disponibilidad depende del proveedor.",
    },
    {
        "id": "heraldo_mexico",
        "nombre": "El Heraldo de México",
        "tipo": "rss",
        "pais": "México",
        "idioma": "es",
        "base_url": "https://heraldodemexico.com.mx",
        "urls": [
            "https://heraldodemexico.com.mx/rss/",
            "https://heraldodemexico.com.mx/rss/feed.html",
        ],
        "dominios_permitidos": ["heraldodemexico.com.mx", "www.heraldodemexico.com.mx"],
        "activo": True,
        "limite_noticias": 20,
        "delay_segundos": 3,
        "requiere_parser_html": False,
        "notas": "Canales RSS públicos. Puede requerir ajuste si el sitio cambia sus feeds.",
    },
    {
        "id": "inegi_sala_prensa",
        "nombre": "INEGI Sala de Prensa",
        "tipo": "html",
        "pais": "México",
        "idioma": "es",
        "base_url": "https://www.inegi.org.mx",
        "urls": [
            "https://www.inegi.org.mx/app/saladeprensa/",
        ],
        "dominios_permitidos": ["www.inegi.org.mx", "inegi.org.mx"],
        "activo": True,
        "limite_noticias": 20,
        "delay_segundos": 3,
        "requiere_parser_html": True,
        "notas": "Página HTML institucional; puede requerir parser específico si cambia el DOM.",
    },
]
